export const LOAD_POSTS = "LOAD_POSTS"  
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"  
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE"

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const GET_PARTICULAR_POST = "GET_PARTICULAR_POST"

